import React from "react";

class PrivacyPolicyPage extends React.Component {
  componentDidMount() {
    window.scrollTo(0, 0);
  }
  
  render() {
    return (
      <>        
        <div className="main-content">
          <div className="container"> 
            <div className="row">
              <div className="col-md-12">
                <h2 className="font-weight-bold mt-5 mb-4">Privacy Policy TEXQUE</h2>
                <p><em>Last updated: February 20, 2020</em></p>
                <p>TEXQUE and the company whose branding is displayed on the website ("<strong>Site</strong>") and/or mobile application ("<strong>Application</strong>") that links to this Privacy Policy (the "<strong>Branded Company</strong>") respect the privacy of Site and Application (collectively, "<strong>Services</strong>") users.</p>
                <p>This Privacy Policy is intended to inform you of the policies and practices regarding the collection, use and disclosure of any personal information that TEXQUE collects from or about users in connection with the Services. TEXQUE provides the Services to users on behalf of the Branded Company, as a service provider and data processor. This Privacy Policy does not apply to any websites, mobile applications or other online services that do not link to this policy, including other services provided by the Branded Company. To the extent TEXQUE shares personal information with the Branded Company as this Privacy Policy describes, this Privacy Policy does not apply to the Branded Company&rsquo;s subsequent use of that information.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>INTERNATIONAL DATA TRANSFERS AND PRIVACY SHIELD</strong></p>
                <p>If you are a non-U.S. user of the Services, by using the Services and providing us with data, you acknowledge and agree that your personal information may be processed outside the country in which it was collected, including the United States, where laws regarding processing of personal information may be less stringent than the laws in your country. By providing your data, you acknowledge such transfer.</p>
                <p>TEXQUE complies with the EU-US and Swiss-US Privacy Shield Frameworks as set forth by the US Department of Commerce regarding the collection, use, and retention of personal information from the EU and/or Switzerland.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>THE TYPES OF INFORMATION TEXQUE COLLECTS</strong></p>
                <p>TEXQUE collects information from you in various ways when you access or use the Services. TEXQUE collect personal information from you in the following ways:</p>
                <p>(a) Personal Information You Provide to Us. For example:</p>
                <ul>
                  <li>TEXQUE may collect personal information from you, such as your first and last name, address, e-mail, telephone number and when you create an account ("<strong>Account</strong>").</li>
                  <li>The Services allow you to store preferences such as your location, recent orders and favorite menu items in order to make it more convenient for you to place additional orders in the future.</li>
                  <li>When you order menu items from the Branded Company on our Services, TEXQUE will collect all information necessary to complete the transaction, including your name and payment information. TEXQUE may store this information on our servers, in order to make it easier for you to place orders for the Branded Company&rsquo;s menu items in the future. TEXQUE does not store your payment information on our servers but stores a secure "token" that helps facilitate a secure payment transaction on the Branded Company Services.</li>
                  <li>If you provide feedback or contact TEXQUE via email, TEXQUE will collect your name and email address, as well as any other content included in the email, in order to send you a reply.</li>
                  <li>TEXQUE also collects other types of personal information that you provide voluntarily, such as any information requested by TEXQUE if you contact TEXQUE via email regarding support for the Services.</li>
                </ul>
                <p>(b) Personal Information Collected Via Technology. TEXQUE collects certain information from you automatically when you access and use the Services as described below:</p>
                <ul>
                  <li>Information Collected by our Servers. To make the Services more useful to you, TEXQUE servers (which may be hosted by a third party service provider) collect information from you, including the referring/exit pages, your browser type, domain name, date/time stamp for your visit and your Internet Protocol (IP) address (a number that is automatically assigned to your computer or device when you use the Internet). TEXQUE uses this information to analyze trends, administer the Services, monitor for fraudulent activities using fraud management tools, and better tailor the Services to users&rsquo; needs.</li>
                  <li>Like many online services, TEXQUE uses cookies to collect information on the Sites. "Cookies" are small pieces of information that a web site sends to your computer's hard drive while you are viewing a web site. TEXQUE may use both session cookies (which expire once you close your web browser) and persistent cookies (which stay on your computer until you delete them) to provide you with a more personal and interactive experience on the Sites. This type of information is collected to make the Services more useful to you and to tailor your experience with the Services to meet your special interests and needs.</li>
                  <li>Mobile Services. We may also collect information from your mobile device if you have downloaded a Branded Company&rsquo;s Application. This information is generally used to help deliver the most relevant information to you. Examples of information that may be collected and used include your general geographic location, how you use the Application(s), and information about the type of device you use. In addition, in the event the Application crashes your mobile device, TEXQUE will receive information about your mobile device model, software version and device carrier, to identify and fix bugs and otherwise improve the performance of the Application. This information is sent to TEXQUE as aggregated information. The aggregated information is not traceable to any individual and cannot be used to identify an individual.</li>
                  <li>Third Party Analytics. TEXQUE uses third party service providers to help analyze how users use the Services ("Analytics Companies"). These Analytics Companies use Cookies to collect information such as how often users visit the Site, what pages they visit and what other sites they used prior to coming to the Site. TEXQUE uses the information we get from these Analytics Companies to improve the Services.</li>
                </ul>
                <p>(c) Facebook and other Social Networking Services. The Services may allow users to access Facebook and other social networking sites (each, an "SNS") to interact with and share their experiences with the Branded Company&rsquo;s products and services with their friends. If you are not a registered user of the Services, you can create an Account by clicking on "Sign In" using Facebook or another SNS that we support, and then entering your SNS login credentials. In this case, TEXQUE may receive information from Facebook or another SNS to make it easier for you to create an Account on the Services. Once you register on the Services and connect with Facebook or another SNS, you will be able to automatically post recent activity back to Facebook or the other SNS. The information that your Facebook or other SNS account provides to TEXQUE may depend on the privacy settings you have with that SNS, so please consult the SNS&rsquo;s privacy and data practices.</p>
                <p>(d) Location Information. If you have enabled location services on your phone and agree to the collection of your location when prompted by the Services, TEXQUE will collect your location information when you use the Services; for example, to locate those restaurants and locations of the Branded Company that are near you or when you "check in" via the Services. If you do not want TEXQUE to collect this information, you may decline the collection of your location when prompted or adjust the location services settings on your device.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>HOW TEXQUE USES YOUR INFORMATION</strong></p>
                <p>(a) General Use. In general, TEXQUE uses your personal information to respond to your requests as submitted through the Services, to provide you the Services you request, or to help serve you better. TEXQUE uses your personal information in the following ways:</p>
                <ul>
                  <li>facilitate the creation of, and secure and maintain your Account;</li>
                  <li>identify you as a user and not a potential fraudster in TEXQUE system;</li>
                  <li>provide improved administration of the Site, Application and Services;</li>
                  <li>provide the Services you request;</li>
                  <li>improve the quality of experience when you interact with the Site, Application and Services;</li>
                  <li>send you a welcome e-mail to verify ownership of the e-mail address provided when your Account was created;</li>
                  <li>send you administrative e-mail notifications, such as security or support and maintenance advisories;</li>
                  <li>call or send you an SMS message about your order status or any issues with your order (e.g., food being prepared); and,</li>
                  <li>send surveys, offers, and other promotional materials related to the Services at the Branded Company&rsquo;s request or direction.</li>
                </ul>
                <p>(b) Creation of Anonymous Data. TEXQUE may create anonymous information records from personal information by excluding information (such as your name) that makes the information personally identifiable to you. TEXQUE may use this anonymous information, aggregated with other anonymized user information, to analyze request patterns and usage patterns to enhance TEXQUE products and services. TEXQUE reserves the right to use and disclose anonymous information to third parties in its discretion.</p>
                <p><strong>DISCLOSURE OF YOUR PERSONAL DATA</strong></p>
                <p>TEXQUE discloses your personal data as described below and as described elsewhere in this Privacy Policy.</p>
                <p>(a) At the Direction of the Branded Company. TEXQUE may share your information with the Branded Company or with third parties at the direction of the Branded Company. For example, when you use the Services to place orders, TEXQUE will transmit your information to the Branded Company location you designate, or to the Branded Company&rsquo;s third-party services providers or partners, as directed by the Branded Company, to facilitate your order. Other than as described in this Privacy Policy in connection with the Services, this Privacy Policy does not apply to the processing of your information by the Branded Company or third parties with whom TEXQUE shares information at the Branded Company&rsquo;s direction.</p>
                <p>BECAUSE TEXQUE DOES NOT CONTROL THE PRIVACY PRACTICES OF THE BRANDED COMPANY, YOU SHOULD READ AND UNDERSTAND THE BRANDED COMPANY&rsquo;S PRIVACY POLICIES.</p>
                <p>(b) Third Party Service Providers. TEXQUE may share your personal information with third party service providers that perform services for or on behalf of TEXQUE, for the purposes described in this Privacy Policy, including: to provide you with the Services; to conduct quality assurance testing; to facilitate the creation of Accounts; to optimize the performance of the Services; to provide technical support; and/or to provide other services to TEXQUE.</p>
                <p>(c) Affiliates. TEXQUE may share some or all of your personal information with its parent company, subsidiaries, joint ventures, or other companies under common control ("Affiliates"), in which case TEXQUE will require its Affiliates to honor this Privacy Policy.</p>
                <p>(d) Corporate Restructuring. TEXQUE may share some or all of your personal information in connection with or during negotiation of any merger, financing, acquisition or dissolution transaction involving the sale, transfer, divestiture, or disclosure of all or a portion of TEXQUE business or assets. In the event of an insolvency, bankruptcy, or receivership, personal information may also be transferred as a business asset. If TEXQUE company, business or assets is acquired by another company, that company will possess the personal information collected by TEXQUE and the company will assume the rights and obligations regarding your personal information as described in this Privacy Policy.</p>
                <p>(e) Social Networking Sites ("SNS"). TEXQUE Application and Services may enable you to post content to SNSs (e.g. Facebook and Twitter). If you choose to do this, TEXQUE will provide information to such SNSs in accordance with your elections. You acknowledge and agree that you are solely responsible for your use of those websites and that it is your responsibility to review the terms of use and privacy policy of the third-party provider of such SNSs. TEXQUE will not be liable for: (i) the availability or accuracy of such SNSs; (ii) the content, products or services on or availability of such SNSs; or (iii) your use of any such SNSs.</p>
                <p>(f) Other Disclosures. Regardless of any choices you make regarding your personal information, TEXQUE may disclose your personal information if TEXQUE believes in good faith that such disclosure is necessary (a) to comply with relevant laws or to respond to subpoenas or warrants served on TEXQUE; (b) to protect and defend the rights or property of TEXQUE, the Branded Company or users of the Services; (c) in connection with a legal investigation; and/or (d) to investigate or assist in preventing any violation or potential violation of the law, this Privacy Policy, or TEXQUE Terms of Use.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>A NOTE ABOUT CHILDREN</strong></p>
                <p>The Services are not directed towards individuals under the age of 13, and TEXQUE does not intentionally gather personal information about visitors who are under the age of 13. Furthermore, TEXQUE does not intentionally allow visitors under the age of 18 to register for the Services. If a child under 13 submits personal information to TEXQUE and TEXQUE learns that the personal information is the information of a child under 13, TEXQUE will attempt to delete the information as soon as possible. If you believe that TEXQUE might have any personal information from a child under 13, please contact TEXQUE at: One World Trade Center, 82nd Floor, New York, NY 10007.</p>
                <p><strong>LINKS TO OTHER SITES</strong></p>
                <p>The Site may contain links to third party websites. When you click on a link to any other website or location, you will leave the Site and go to another site and another entity may collect personal and/or anonymous information from you. TEXQUE provision of a link to any other website or location is for your convenience and does not signify TEXQUE endorsement of such other website or location or its contents. TEXQUE has no control over, does not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>YOUR CHOICES REGARDING YOUR INFORMATION</strong></p>
                <p>You have several choices regarding use of information on the Services.</p>
                <p>(a) Cookies. If you decide at any time that you no longer wish to accept cookies from the Services for any of the purposes described above, then you can instruct your browser, by changing its settings, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. Consult your browser&rsquo;s technical information. If you do not accept cookies, however, you may not be able to use all or portions of the Services or all functionality of the Services. If you have any questions about how to disable or modify cookies, please let TEXQUE know at the contact information provided below.</p>
                <p>(b) De-Linking SNS. If you decide at any time that you no longer wish to have your SNS account (e.g., Facebook or Twitter) linked to your Account, then you may close your account with the Branded Company. Please refer to the privacy settings of the SNS to determine how you may adjust our permissions and manage the interactivity between the Services and your social media account or mobile device.</p>
                <p>(c) Application. You can stop all collection of information by the Application by uninstalling the Application. You may use the standard uninstall processes as may be available as part of your mobile device or via the mobile application marketplace or network.</p>
                <p>(d) How We Respond to Do Not Track Signals. Some web browsers transmit "do not track" signals to the websites and other online services with which your web browser communications. There is currently no standard that governs what, if anything, websites should do when they receive these signals. TEXQUE currently does not take action in response to these signals. If and when a standard is established, TEXQUE may revise its policy on responding to these signals.</p>
                <p>(e) Access or Correct Your Information. You may request to review and update the information TEXQUE maintains about you by submitting a request to <strong>PRIVACY@TEXQUE.COM</strong></p>
                <p>(f) Opting Out of SMS Communications. If you provide your phone number through the Services, TEXQUE may send you notifications by SMS, such as to alert you of a problem with your order or to notify you that your delivery is on its way. You may opt out of SMS communications by unlinking your mobile phone number through the Site.</p>
                <p>(g) Opting Out of Location Tracking. If you initially consented to the collection of geo-location information through the Services, you can subsequently stop the collection of this information at any time by changing the preferences on your mobile device. Please note, however, that if you withdraw consent to TEXQUE collection of location information, you may no longer be able to use some features of the Services.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>YOUR CALIFORNIA PRIVACY RIGHTS</strong></p>
                <p>(AS PROVIDED BY CALIFORNIA CIVIL CODE SECTION 1798.83)</p>
                <p>A California resident who has provided personal data to a business with whom he/she has established a business relationship for personal, family, or household purposes (a "California customer") may request information about whether the business has disclosed personal data to any third parties for the third parties&rsquo; direct marketing purposes. In general, if the business has made such a disclosure of personal data, upon receipt of a request by a California customer, the business is required to provide a list of all third parties to whom personal data was disclosed in the preceding calendar year, as well as a list of the categories of personal data that were disclosed. California customers should visit the Branded Company&rsquo;s website for further information on how to submit a request or, if applicable, opt out of the Branded Company&rsquo;s sharing of the customers&rsquo; personal data with third parties for those parties&rsquo; direct marketing purposes.&nbsp;</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>PRIVACY POLICY UPDATES</strong></p>
                <p>This Privacy Policy is subject to occasional revision. TEXQUE will notify you of any material changes in its collection, use, or disclosure of your personal information by posting a notice on the Site and within the Application. Any material changes to this Privacy Policy will be effective thirty (30) calendar days following notice of the changes on the Site and within the Application. These changes will be effective immediately for new users of the Services. If you object to any such changes, you must notify TEXQUE prior to the effective date of such changes that you wish to deactivate your Account. Continued use of the Services following notice of any such changes shall indicate your acknowledgement of such changes.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>CONTACT TEXQUE</strong></p>
                <p>If you have any questions or complaints about this Privacy Policy or TEXQUE data collection or processing practices, or if you want to report any security violations to TEXQUE, please contact TEXQUE by email at:&nbsp;<strong>PRIVACY@TEXQUE.COM</strong></p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>NOTICE TO CALIFORNIA USERS</strong></p>
                <p>We are providing this supplemental privacy notice to California users on behalf of the Branded Company, pursuant to the California Consumer Privacy Act of 2018 ("CCPA"). Please note that as a service provider handling personal information on behalf of the Branded Company, TEXQUE is not required to provide a CCPA notice. This notice does not apply to individuals with whom TEXQUE engages in the individuals&rsquo; capacity as representatives of businesses that may provide services to TEXQUE, or to which TEXQUE may provide its services including any user who visit<strong>&nbsp;<u>www.TEXQUE.com</u></strong>, which is designed only for businesses and not for individuals&rsquo; use in their personal or household capacity.</p>
                <p>The Branded Company is prohibited from selling personal information through the TEXQUE Services. As set out in this Privacy Policy, we, our service providers and partners use cookies and other tracking technologies to analyze website traffic and facilitate advertising. Please visit the Branded Company&rsquo;s homepage for further details about its privacy practices.</p>
                <p>The CCPA grants California residents the following rights.&nbsp;</p>
                <ul>
                  <li>You can request information about how the Branded Company has collected, used and shared your personal information through the TEXQUE Services during the past 12 months.&nbsp;</li>
                  <li><strong>Access</strong>. You can request a copy of the personal information that TEXQUE maintains about you on behalf of the Branded Company.&nbsp;</li>
                  <li>You can ask to delete the personal information that TEXQUE maintains about you on behalf of the Branded Company</li>
                </ul>
                <p>Please note that the CCPA limits these rights by, for example, prohibiting businesses from providing&nbsp;</p>
                <p>certain sensitive information in response to an access request and limiting the circumstances in which&nbsp;</p>
                <p>they must comply with a deletion request.&nbsp;</p>
                <p>You are entitled to exercise the rights described above free from discrimination.&nbsp;</p>
                <p>Here is how you can submit requests:&nbsp;</p>
                <ul>
                  <li><strong>To request access to or deletion of personal information</strong>, visit the Branded Company&rsquo;s website.</li>
                  <li><strong>Identity verification</strong>. CCPA requires verification of the identity of the individual submitting the request. For identity verification requirements, visit the Branded Company&rsquo;s website.&nbsp;</li>
                  <li><strong>Authorized agents</strong>. California residents can empower an "authorized agent" to submit requests on their behalf.&nbsp;</li>
                </ul>
                <p>&nbsp;</p>
              </div>
            </div>  
          </div>
        </div>
      </>
    );
  }
}

export default PrivacyPolicyPage;
